config/routes.rb
App::Application.routes.draw do
    
  resources :followers, only: [:create, :destroy]
  devise_for :users
  
  get "home/index"
  resources :users, only: [:index]
  get '/users/show/:id', to: 'users#show', as: 'user'
  resources :recommendations
  get "dashboard", to: "users#dash"
  root 'home#index'

end

app/models/follower.rb
class Follower < ActiveRecord::Base
  belongs_to :follower, :class_name => "User"
  belongs_to :followee, :class_name => "User"
  validates :follower_id, uniqueness: {scope: :followee_id, message: "You've already followed this person.  They can't be thaaaaat cool."}
end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: {maximum: 1000}
  validates :title, length: {maximum: 50}
  validates :title, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :followers, :dependent => :destroy
    has_many :recommendations, :dependent => :destroy
	validates :password, confirmation: true    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
before_filter :configure_permitted_parameters, if: :devise_controller?
protected
def configure_permitted_parameters
 devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, 
:password_confirmation) }
 devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, 
:password_confirmation, :current_password) }
end

end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
	


	def create
		@follower = Follower.new(follower_params)
		if @follower.save
			#will send notification to followee
			Notifications.followed(@follower).deliver
			redirect_to users_path
		else
			redirect_to users_path
		end
	end

	def destroy
		@follower = Follower.find(params[:id])
		@follower.destroy
		redirect_to users_path
	end

	def follower_params
		params.require(:follower).permit(:follower_id, :followee_id)
	end	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
 def index
  @recommendations = Recommendation.all.order(:user_id)
end

def new
  if user_signed_in?
    @recommendation = Recommendation.new
  else
    redirect_to new_user_session_path
  end 
end

def create
  @recommendation = Recommendation.new(recommendation_params)
  if @recommendation.user_id != current_user.id
    redirect_to recommendation_path
  else
    if @recommendation.save
      Notifications.new_recommendation(current_user).deliver
      redirect_to recommendations_path
    else
      render 'new'
    end
  end
end

def edit
  if user_signed_in?
    @recommendation = Recommendation.find(params[:id])
  else
    redirect_to new_user_session_path
  end
end

def update
  @recommendation = Recommendation.find(params[:id])
  if @recommendation.user_id != current_user.id
    render 'edit'
  else 
    if @recommendation.update_attributes(recommendation_params)
      redirect_to recommendation_path(@recommendation.id)
    else
      render 'edit'
    end
  end    
end

def show
 @recommendation = Recommendation.find(params[:id])
end

def destroy
  @recommendation = Recommendation.find(params[:id])
  @recommendation.destroy
  redirect_to recommendations_path
end

private
def recommendation_params
  params.require(:recommendation).permit(:title, :body, :user_id)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else 
      render 'new'
    end 
  end


  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user= User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end  
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  def show
    @user = User.find(params[:id])
    @recommendations = Recommendation.where(user_id: @user.id).order(:title).limit(5)
    @followers = Follower.where(followee_id: @user.id)
    @following = Follower.where(follower_id: @user.id)
  end

  def dash 
    if user_signed_in?
      @user = current_user
      @followers = Follower.where(follower_id: current_user.id)
    else
      redirect_to users_path
    end
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Welcome to MovieReviews!</h1>
<ul>
	<%=link_to "New Recommendation", new_recommendation_path%>
	<%=link_to "View Users", users_path%>
	<%=link_to "View Recommendations", recommendations_path%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%=notice%></p>
<p class="alert"><%alert%></p>
<div class="navbar">
	<ul class="nav">
		<% if !user_signed_in? %>
		<li>
			<%=button_to 'Login', new_user_session_path, :class => "nav-link" %>
		</li>
		<%else%>
		<li>
			<%=button_to 'Logout', destroy_user_session_path, :method => :delete, :class => "nav-link" %>
		</li>
		<li>
			<%=button_to 'Edit User', edit_user_registration_path, :method =>:get, :class => "nav-link"%>
		</li> 

		<%end%>
		<li>
			<%=button_to "Home", root_path, :method => :get, :class => "nav-link" %>
		</li>
	</ul>	
</div>
<%= yield %>

</body>
</html>

app/views/notifications/followed.html.erb
<h2><%= @greeting %></h2>

<p><%= @follower %> followed you!  You can check out their page <a href=<%=user_url(@id) %>>here</a> </p>

app/views/notifications/new_recommendation.text.erb

<%= @greeting %>, <%= @user%>, you just created a new Movie Review! You da bomb!

app/views/recommendations/edit.html.erb
<%=form_for(@recommendation) do |f|%>
	<div class="field">
		<p><b>Title</b></p>
		<%=f.text_field :title%>
	</div>
	<div class="field">
		<p><b>Body</b></p>
		<%=f.text_field :body%>
	</div>
	<div class="field">
		<%=f.hidden_field :user_id, :value=>current_user.id%>
	</div>
	<div class="actions">
		<%=f.submit%>
	</div>
<%end%>

<div class="error-msg">
	<%if @recommendation.errors.any? %>
	<ul>
		<% @recommendation.errors.full_messages.each do |msg| %>
		<li><%=msg%></li>
		<%end%>
	</ul>
	<%end%>
</div>	

app/views/recommendations/index.html.erb
<table>
	<tr>
		<div class = "rec-info">
			<td><b>Title</b></td>
			<td><b>User</b></td>
		</div>
	</tr>
	<%@recommendations.each do |recommendation| %>
	<tr>
		<td><%=link_to recommendation.title, recommendation_path(recommendation.id)%></td>
		<td><%=recommendation.user.name unless recommendation.user.nil?%></td>
		<% if current_user.id == recommendation.user.id %>
			<td><%=link_to "Edit", edit_recommendation_path(recommendation.id)%> </td>
			<td><%=button_to "Destroy", recommendation, method: :delete %></td>
		<%end%>
	</tr>
	<%end%>
</table>

app/views/recommendations/new.html.erb
<%=form_for(@recommendation) do |f| %>
	<div class="field">
		<p><b>Title</b></p>
		<%=f.text_field :title%>
	</div>
	<div class="field">
		<p><b>Body</b></p>
		<%=f.text_area :body%>
	</div>
	<div class="field">
		<p><b>User</b></p>
		<%=f.hidden_field :user_id, :value=>current_user.id%>
	</div>
	<div class="actions">
		<%= f.submit%>
	</div>
<%end%>	

<div class="error-msg">
	<%if @recommendation.errors.any? %>
	<ul>
		<% @recommendation.errors.full_messages.each do |msg| %>
		<li><%=msg%></li>
		<%end%>
	</ul>
	<%end%>
</div>	

app/views/recommendations/show.html.erb
<div>
	<h2>Recommendation</h2>
	<h4>Title:</h4>
	<p><%=@recommendation.title%></p>
	<h4>Body:</h4>
	<p><%=@recommendation.body%></p>
	<h4>User:</h4>
	<p><%=@recommendation.user.name unless @recommendation.user.nil?%></p>
</div>

app/views/users/dash.html.erb
<h2><%=current_user.name%> </h2>



<% @recommendations.each do |recommendation| %>
	<div class="dash-review">
		<h2><%= link_to recommendation.title, recommendation_path(recommendation.id)%></h2>
		<p><%= recommendation.user.name%></p>
		<p><%= recommendation.body%></p>
	</div>
<%end%>

app/views/users/edit.html.erb
<%=form_for(@user) do |f|%>
	<div class="field">
		<p><b>Name</b></p>
		<%=f.text_field :name%>
	</div>
	<div class="field">
		<p><b>Email</b></p>
		<%=f.text_field :email%>
	</div>
	<div class="field">
		<p><b>Password</b></p>
		<%=f.text_field :password%>
	</div>
	<div class="actions">
		<%=f.submit%>
	</div>
<%end%>

app/views/users/index.html.erb
<table>
	<tr>
		<td><b>Name</b></td>
		<td><b>Email</b></td>
	</tr>
	<%@users.each do |user|%>
	
	<tr>
		<div class="user-link">
		<td><%=link_to user.name, user_path(user.id)%></td>
		</div>
		<td><%=user.email%></td>
			<% if user_signed_in? %>
			<% if user.id != current_user.id %>
			<% if Follower.where("follower_id = ? AND followee_id = ?", current_user.id, user.id).empty? %>
				<td><%=form_for (Follower.new) do |f| %>
					<div class="field">
						<%= f.hidden_field :follower_id, :value => current_user.id%>
					</div>
					<div class="field">
						<%= f.hidden_field :followee_id, :value => user.id%>
					</div>
					<div class="field">
						<%= f.hidden_field :followee_name, :value => user.name%>
						<%= f.hidden_field :follower_name, :value => current_user.name%>
					</div>
					<div class="actions">
							<%= f.submit "Follow" %>
					</div>
				<%end %> </td>
			<%else%>
					<td><%= button_to "Unfollow", Follower.where("follower_id = ? AND followee_id = ?", current_user.id, user.id).take!, method: :delete %>
					</td>
			<%end%>
			<%end%>
			<% end %>
	</tr>
		<%end%>
</table>	

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
	<div class="field">
		<p><b>Name</b></p> 
		<%= f.text_field :name%>
	</div>
	<div class="field">
		<p><b>Email</b></p> 
		<%= f.text_field :email%>
	</div>
	<div class="field">
		<p><b>Password</b></p> 
		<%= f.password_field :password%>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/users/show.html.erb
<div class= "User-Dashboard">
	<h2><%=@user.name%>'s User Information:</h2>
	<h4>Email:</h4>
	<p><%=@user.email%></p>
	<h4>Following:</h4>
	<table>
	<% @following.each do |follow| %>
	<tr>
		<div class = "following">
			<td><%= link_to follow.followee.name, user_path(follow.followee_id)%></td>
		</div>
	</tr>
	<%end%>
	</table>
	<h4>Followed By:</h4>
	<table>
	<% @followers.each do |follow| %>
	<tr>
		<div class="followers">
		<td><%= link_to follow.follower.name, user_path(follow.follower.id)%></td>
		</div>
	</tr>
	<%end%>
	</table>
</div>

	


<h2><%= @user.name%>'s Recommendations:</h2>
<%@recommendations.each do |recommendation|%>
	<div class="dash-review">
		<h><%=link_to recommendation.title, recommendation_path(recommendation.id)%></h2>
		<p><%=recommendation.body%></p>
	</div>
<%end%>

<button class="hide-btn">Hide Recommendations</button>